name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - name: Print NPM modules after install
        run: du -d 0 -h ~/.npm || true
