name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Print cached NPM modules size
        run: du -d 0 -h ~/.npm

      - name: Install
        run: npm ci

      - name: Print NPM modules after install
        run: du -d 0 -h ~/.npm
